// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQpgzlVagJEBjfu7ZDe-XFWd82kE35Xhc',
    appId: '1:581118858705:android:040a0691025ddf6952fcf0',
    messagingSenderId: '581118858705',
    projectId: 'hafefly-android',
    databaseURL: 'https://hafefly-android-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hafefly-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5WZtaQmjDzFcihJTSsG3Up1gnauWY43M',
    appId: '1:581118858705:ios:4b552cdac6ce90e752fcf0',
    messagingSenderId: '581118858705',
    projectId: 'hafefly-android',
    databaseURL: 'https://hafefly-android-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hafefly-android.appspot.com',
    iosClientId: '581118858705-qilhdhtgba7m362m7j7iiovlf3s1k90t.apps.googleusercontent.com',
    iosBundleId: 'com.raynmore.nhafeflek',
  );
}
