# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a Flutter apk"
  lane :build do |options|
    # sh "./flutter_build.sh --clean" TODO: uncomment this line when publishing to play store;
    sh "./flutter_build.sh --apk"
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Submit a new Beta Build to AppCenter"
  lane :deploy do
  if File.exist?(File.dirname(__FILE__) + "./../build/app/outputs/apk/release/app-release.apk")
    appcenter_upload(
      api_token: "97a13fd57f697d52c44943cf04c7cabc2bf01acf", # Your secret api token from app center
      owner_name: "raynex", # Your username on AppCenter
      app_name: "nhafeflek", # Your AppCenter name
      apk: "../build/app/outputs/apk/release/app-release.apk",
    )

#    upload_to_play_store(
#      track: options[:production] ? 'production' : options[:internal] ? 'internal' : options[:alpha] ? 'alpha' : 'beta',
#      aab: '../build/app/outputs/bundle/release/app.aab',
#      skip_upload_images: true,
#      skip_upload_screenshots: true,
#    ) TODO: uncomment this line when publishing to play store;
    else
      UI.message('Unable to find apk')
    end
  end
end
